In [ ]:
import pandas as pd

# URL del archivo
url = "https://raw.githubusercontent.com/AngyArango-G2/Reto-Tecnologico-Grupo2/refs/heads/main/data/raw/Accidentes_de_tr%C3%A1nsito_reportados_en_los_municipios_que_tienen_convenio_con_la_Gerencia_de_Seguridad_Vial_de_Antioquia_20260428.csv"

# Cargar base
df = pd.read_csv(url)

# Ver primeras filas
df.head()

,FECHA ACCIDENTE,HORA ACCIDENTE,GRAVEDAD,CLASE ACCIDENTE,CAUSANTE ACCIDENTE,DESCRIPCIÓN COLISIONANTE,DESCRIPCIÓN OBJETO FIJO,ZONA ACCIDENTE,DESCRIPCIÓN DE ESTADO,ÁREA ACCIDENTE,...,DESCRIPCIÓN LOCALIZACIÓN,ESTADO CLIMA,MUNICIPIO,DIRECCIÓN LUGAR,NUMERO VICTIMA PEATÓN,NUMERO VICTIMA ACOMPAÑANTE,NUMERO VICTIMA PASAJERO,NUMERO VICTIMA CONDUCTOR,NUMERO VICTIMA HERIDO,NUMERO VICTIMA MUERTO
0,04/11/2014,06:01,h,CHOQUE,Ciclista-Motociclista,VEHÍCULO,NO REPORTADO,NO REPORTADO,FALLADO,RURAL,...,TRAMO DE VÍA,NORMAL,AMAGA,KM 2,0,0,0,0,0,0
1,17/05/2015,11:05,d,CHOQUE,Ciclista-Motociclista,VEHÍCULO,NO REPORTADO,NO REPORTADO,FALLADO,URBANA,...,TRAMO DE VÍA,NORMAL,AMAGA,CALLE 47 49 64,0,0,0,0,0,0
2,11/06/2014,12:01,h,VOLCAMIENTO,Ciclista-Motociclista,NO REPORTADO,NO REPORTADO,NO REPORTADO,PEND. NOTIFICACIÓN,URBANA,...,TRAMO DE VÍA,NORMAL,NO REPORTA,CALLE 20 CON CARRERA 20,0,0,0,0,0,0
3,09/03/2014,09:01,d,CHOQUE,Ciclista-Motociclista,VEHÍCULO,NO REPORTADO,NO REPORTADO,FALLADO,RURAL,...,TRAMO DE VÍA,NORMAL,NO REPORTA,TRONCAL DEL CAFÉ SECTOR EL LICEO,0,0,0,0,0,0
4,28/04/2014,21:01,h,CAÍDA OCUPANTE,Ciclista-Motociclista,NO REPORTADO,NO REPORTADO,NO REPORTADO,FALLADO,RURAL,...,TRAMO DE VÍA,NORMAL,NO REPORTA,VEREDA LA CLARITA,0,0,0,0,0,0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 846 entries, 0 to 845
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   FECHA ACCIDENTE             846 non-null    object
 1   HORA ACCIDENTE              846 non-null    object
 2   GRAVEDAD                    846 non-null    object
 3   CLASE ACCIDENTE             846 non-null    object
 4   CAUSANTE ACCIDENTE          846 non-null    object
 5   DESCRIPCIÓN COLISIONANTE    846 non-null    object
 6   DESCRIPCIÓN OBJETO FIJO     846 non-null    object
 7   ZONA ACCIDENTE              846 non-null    object
 8   DESCRIPCIÓN DE ESTADO       846 non-null    object
 9   ÁREA ACCIDENTE              846 non-null    object
 10  SECTOR ACCIDENTE            846 non-null    object
 11  DESCRIPCIÓN LOCALIZACIÓN    846 non-null    object
 12  ESTADO CLIMA                846 non-null    object
 13  MUNICIPIO                   846 non-null    object
 14  DIRECCIÓN LUGAR             846 non-null    object
 15  NUMERO VICTIMA PEATÓN       846 non-null    int64
 16  NUMERO VICTIMA ACOMPAÑANTE  846 non-null    int64
 17  NUMERO VICTIMA PASAJERO     846 non-null    int64
 18  NUMERO VICTIMA CONDUCTOR    846 non-null    int64
 19  NUMERO VICTIMA HERIDO       846 non-null    int64
 20  NUMERO VICTIMA MUERTO       846 non-null    int64
dtypes: int64(6), object(15)
memory usage: 138.9+ KB

In [ ]:
df.isnull().sum()

FECHA ACCIDENTE               0
HORA ACCIDENTE                0
GRAVEDAD                      0
CLASE ACCIDENTE               0
CAUSANTE ACCIDENTE            0
DESCRIPCIÓN COLISIONANTE      0
DESCRIPCIÓN OBJETO FIJO       0
ZONA ACCIDENTE                0
DESCRIPCIÓN DE ESTADO         0
ÁREA ACCIDENTE                0
SECTOR ACCIDENTE              0
DESCRIPCIÓN LOCALIZACIÓN      0
ESTADO CLIMA                  0
MUNICIPIO                     0
DIRECCIÓN LUGAR               0
NUMERO VICTIMA PEATÓN         0
NUMERO VICTIMA ACOMPAÑANTE    0
NUMERO VICTIMA PASAJERO       0
NUMERO VICTIMA CONDUCTOR      0
NUMERO VICTIMA HERIDO         0
NUMERO VICTIMA MUERTO         0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
# Limpiar nombres de columnas
df.columns = df.columns.str.strip().str.upper().str.replace(" ", "_")

# Limpiar textos
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip().str.upper()

# Ver columnas
print(df.columns)

Index(['FECHA_ACCIDENTE', 'HORA_ACCIDENTE', 'GRAVEDAD', 'CLASE_ACCIDENTE',
       'CAUSANTE_ACCIDENTE', 'DESCRIPCIÓN_COLISIONANTE',
       'DESCRIPCIÓN_OBJETO_FIJO', 'ZONA_ACCIDENTE', 'DESCRIPCIÓN_DE_ESTADO',
       'ÁREA_ACCIDENTE', 'SECTOR_ACCIDENTE', 'DESCRIPCIÓN_LOCALIZACIÓN',
       'ESTADO_CLIMA', 'MUNICIPIO', 'DIRECCIÓN_LUGAR', 'NUMERO_VICTIMA_PEATÓN',
       'NUMERO_VICTIMA_ACOMPAÑANTE', 'NUMERO_VICTIMA_PASAJERO',
       'NUMERO_VICTIMA_CONDUCTOR', 'NUMERO_VICTIMA_HERIDO',
       'NUMERO_VICTIMA_MUERTO'],
      dtype='object')

In [ ]:
df["MUNICIPIO"].value_counts().head(10)

MUNICIPIO
NO REPORTA    359
AMAGA          84
FREDONIA       75
GUARNE         71
ANTIOQUIA      47
CAICEDO        23
ABEJORRAL      22
BETANIA        16
LA UNIÓN       15
COCORNA        14
Name: count, dtype: int64

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/AngyArango-G2/Reto-Tecnologico-Grupo2/refs/heads/main/data/raw/Numero_de_Pasajeros_que_salieron_desde_las_Terminales_de_Transporte_de_Medell%C3%ADn_en_Junio_a%C3%B1o_2019_20260416.csv"

df2 = pd.read_csv(url)

df2.head()

,idsucursal,Nombrecomercial,Fecha_programada,Hora_programada,FechaSalida,HoraSalida,NombreVia,NumPasajeros,Ruta2,DEPARTAMENTO,Ciudad-Dpto
0,Terminal Sur,FLOTA OCCIDENTAL S.A.,2019 Jun 01 12:00:00 AM,1899 Dec 31 12:15:00 AM,2019 Jun 01 12:00:00 AM,1899 Dec 31 12:26:00 AM,PEREIRA,40,ARMENIA(QUINDIO),QUINDIO,ARMENIA(QUINDIO)-QUINDIO
1,Terminal Sur,FLOTA OCCIDENTAL S.A.,2019 Jun 01 12:00:00 AM,1899 Dec 31 12:35:00 AM,2019 Jun 01 12:00:00 AM,1899 Dec 31 12:54:00 AM,PEREIRA,38,ARMENIA(QUINDIO),QUINDIO,ARMENIA(QUINDIO)-QUINDIO
2,Terminal Sur,FLOTA OCCIDENTAL S.A.,2019 Jun 01 12:00:00 AM,1899 Dec 31 12:40:00 AM,2019 Jun 01 12:00:00 AM,1899 Dec 31 12:58:00 AM,PEREIRA,40,ARMENIA(QUINDIO),QUINDIO,ARMENIA(QUINDIO)-QUINDIO
3,Terminal Sur,EXPRESO TREJOS LTDA,2019 Jun 01 12:00:00 AM,1899 Dec 31 12:50:00 AM,2019 Jun 01 12:00:00 AM,1899 Dec 31 12:58:00 AM,LA FELISA,33,CALI,VALLE DEL CAUCA,CALI-VALLE DEL CAUCA
4,Terminal Sur,FLOTA MAGDALENA S.A.,2019 Jun 01 12:00:00 AM,1899 Dec 31 03:15:00 AM,2019 Jun 01 12:00:00 AM,1899 Dec 31 03:23:00 AM,ANSERMA,25,CALI,VALLE DEL CAUCA,CALI-VALLE DEL CAUCA

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85502 entries, 0 to 85501
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   idsucursal        85502 non-null  object
 1   Nombrecomercial   85502 non-null  object
 2   Fecha_programada  85502 non-null  object
 3   Hora_programada   85502 non-null  object
 4   FechaSalida       85502 non-null  object
 5   HoraSalida        85502 non-null  object
 6   NombreVia         85502 non-null  object
 7   NumPasajeros      85502 non-null  int64
 8   Ruta2             85502 non-null  object
 9   DEPARTAMENTO      85502 non-null  object
 10  Ciudad-Dpto       85502 non-null  object
dtypes: int64(1), object(10)
memory usage: 7.2+ MB

In [ ]:
df2.isnull().sum()

idsucursal          0
Nombrecomercial     0
Fecha_programada    0
Hora_programada     0
FechaSalida         0
HoraSalida          0
NombreVia           0
NumPasajeros        0
Ruta2               0
DEPARTAMENTO        0
Ciudad-Dpto         0
dtype: int64

In [ ]:
df2.duplicated().sum()

np.int64(203)

In [ ]:
print(df2.columns)

Index(['idsucursal', 'Nombrecomercial', 'Fecha_programada', 'Hora_programada',
       'FechaSalida', 'HoraSalida', 'NombreVia', 'NumPasajeros', 'Ruta2',
       'DEPARTAMENTO', 'Ciudad-Dpto'],
      dtype='object')

In [ ]:
# Copia base
df2_clean = df2.copy()

# Eliminar duplicados
df2_clean = df2_clean.drop_duplicates()

# Renombrar columnas
df2_clean.columns = df2_clean.columns.str.strip().str.upper()

# Limpiar textos
for col in df2_clean.select_dtypes(include='object').columns:
    df2_clean[col] = df2_clean[col].astype(str).str.strip().str.upper()

print(df2_clean.shape)

(85299, 11)

In [ ]:
df2_clean["FECHA_PROGRAMADA"] = pd.to_datetime(df2_clean["FECHA_PROGRAMADA"], errors="coerce")
df2_clean["FECHASALIDA"] = pd.to_datetime(df2_clean["FECHASALIDA"], errors="coerce")

df2_clean["HORA_PROGRAMADA"] = pd.to_datetime(df2_clean["HORA_PROGRAMADA"], errors="coerce").dt.time
df2_clean["HORASALIDA"] = pd.to_datetime(df2_clean["HORASALIDA"], errors="coerce").dt.time

/tmp/ipykernel_10296/3841976859.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df2_clean["FECHA_PROGRAMADA"] = pd.to_datetime(df2_clean["FECHA_PROGRAMADA"], errors="coerce")
/tmp/ipykernel_10296/3841976859.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df2_clean["FECHASALIDA"] = pd.to_datetime(df2_clean["FECHASALIDA"], errors="coerce")
/tmp/ipykernel_10296/3841976859.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df2_clean["HORA_PROGRAMADA"] = pd.to_datetime(df2_clean["HORA_PROGRAMADA"], errors="coerce").dt.time
/tmp/ipykernel_10296/3841976859.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df2_clean["HORASALIDA"] = pd.to_datetime(df2_clean["HORASALIDA"], errors="coerce").dt.time

In [ ]:
df2_clean.head()

,IDSUCURSAL,NOMBRECOMERCIAL,FECHA_PROGRAMADA,HORA_PROGRAMADA,FECHASALIDA,HORASALIDA,NOMBREVIA,NUMPASAJEROS,RUTA2,DEPARTAMENTO,CIUDAD-DPTO
0,TERMINAL SUR,FLOTA OCCIDENTAL S.A.,2019-06-01,00:15:00,2019-06-01,00:26:00,PEREIRA,40,ARMENIA(QUINDIO),QUINDIO,ARMENIA(QUINDIO)-QUINDIO
1,TERMINAL SUR,FLOTA OCCIDENTAL S.A.,2019-06-01,00:35:00,2019-06-01,00:54:00,PEREIRA,38,ARMENIA(QUINDIO),QUINDIO,ARMENIA(QUINDIO)-QUINDIO
2,TERMINAL SUR,FLOTA OCCIDENTAL S.A.,2019-06-01,00:40:00,2019-06-01,00:58:00,PEREIRA,40,ARMENIA(QUINDIO),QUINDIO,ARMENIA(QUINDIO)-QUINDIO
3,TERMINAL SUR,EXPRESO TREJOS LTDA,2019-06-01,00:50:00,2019-06-01,00:58:00,LA FELISA,33,CALI,VALLE DEL CAUCA,CALI-VALLE DEL CAUCA
4,TERMINAL SUR,FLOTA MAGDALENA S.A.,2019-06-01,03:15:00,2019-06-01,03:23:00,ANSERMA,25,CALI,VALLE DEL CAUCA,CALI-VALLE DEL CAUCA

In [ ]:
df2_clean.groupby("IDSUCURSAL")["NUMPASAJEROS"].sum().sort_values(ascending=False)

IDSUCURSAL
TERMINAL NORTE    903636
TERMINAL SUR      215438
Name: NUMPASAJEROS, dtype: int64

In [ ]:
df2_clean.groupby("CIUDAD-DPTO")["NUMPASAJEROS"].sum().sort_values(ascending=False).head(10)

CIUDAD-DPTO
RIONEGRO-ANTIOQUIA                 123756
MARINILLA-ANTIOQUIA                 61585
GUARNE-ANTIOQUIA                    46954
BOGOTA-ANTIOQUIA                    37793
SANTA FE DE ANTIOQUIA-ANTIOQUIA     34879
CALI-VALLE DEL CAUCA                33179
SAN PEDRO DE MILAGROS-ANTIOQUIA     31457
EL CARMEN DE VIBORAL-ANTIOQUIA      31303
EL SANTUARIO-ANTIOQUIA              27834
ARMENIA(QUINDIO)-QUINDIO            27304
Name: NUMPASAJEROS, dtype: int64

In [ ]:
df2_clean.groupby("NOMBRECOMERCIAL")["NUMPASAJEROS"].sum().sort_values(ascending=False).head(10)

NOMBRECOMERCIAL
COONORTE                                       81228
SOTRAURABA                                     59601
SOTRAMAR                                       56213
COOPETRANSA                                    55408
RAPIDO MEDELLIN RIONEGRO S.A.                  49345
SOTRAGUR S.A                                   46954
GOMEZ HERNANDEZ                                44021
SOTRASANVICENTE  & GUATAPE LA PIEDRA S.C.A.    38547
RAPIDO OCHOA                                   37851
TRANSORIENTE                                   35915
Name: NUMPASAJEROS, dtype: int64

In [ ]:
df2_clean.to_csv("data/processed/pasajeros_terminales_limpia.csv", index=False)

OSError: Cannot save file into a non-existent directory: 'data/processed'

In [ ]:
import os

os.makedirs("data/processed", exist_ok=True)

In [ ]:
df2_clean.to_csv("data/processed/pasajeros_terminales_limpia.csv", index=False)

In [ ]:
os.listdir("data/processed")

['pasajeros_terminales_limpia.csv']

In [ ]:
df2_clean.to_csv("pasajeros_terminales_limpia.csv", index=False)

In [ ]:
import pandas as pd

df3 = pd.read_csv("velocidad_y_tiempo_de_viaje_GT.csv")
df3.head()

FileNotFoundError: [Errno 2] No such file or directory: 'velocidad_y_tiempo_de_viaje_GT.csv'

In [ ]:
import os
os.listdir('/content')

['.config',
 '.ipynb_checkpoints',
 'data',
 'pasajeros_terminales_limpia.csv',
 'Velocidad_y_tiempo_de_viaje_GT.csv',
 'sample_data']

In [ ]:
import pandas as pd

df3 = pd.read_csv("Velocidad_y_tiempo_de_viaje_GT.csv")

df3.head()

/tmp/ipykernel_10296/50133199.py:3: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df3 = pd.read_csv("Velocidad_y_tiempo_de_viaje_GT.csv")

,ID,FECHA_HORA,TV_[S],CORREDOR,DÍA,MES,AÑO,HORA,FECHA,NOMBRE_CORREDOR,Flujo_tipo,SENTIDO,INICIO,FIN,LONGITUD_KM,TV_MINUTOS,VELOCIDAD_KM/H,TV_MIN/KM,DIASEM,NOMBRE_DÍA
0,1210,1/02/2017 6:00,377,2,1,2,2017,6,1/02/2017,Avenida Regional,Continuo,SN,Tugo,San Juan,6.6,6.3,63.0,1.0,3,Mi�rcoles
1,1212,1/02/2017 6:00,495,4,1,2,2017,6,1/02/2017,Autopista Sur,Continuo,NS,CTI,Calle 10,6.5,8.3,47.0,1.3,3,Mi�rcoles
2,1213,1/02/2017 6:00,495,5,1,2,2017,6,1/02/2017,Autopista Norte,Continuo,NS,Solla,Punto Cero,5.3,8.3,39.0,1.6,3,Mi�rcoles
3,1214,1/02/2017 6:00,401,6,1,2,2017,6,1/02/2017,Autopista Norte,Continuo,SN,Punto Cero,Solla,5.3,6.7,48.0,1.3,3,Mi�rcoles
4,1215,1/02/2017 6:00,693,7,1,2,2017,6,1/02/2017,Avenida 80,Interrumpido,NS,Calle 65,Calle 30,5.1,11.6,26.0,2.3,3,Mi�rcoles

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 682502 entries, 0 to 682501
Data columns (total 20 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ID               682502 non-null  object
 1   FECHA_HORA       682502 non-null  object
 2   TV_[S]           682502 non-null  int64
 3   CORREDOR         682502 non-null  int64
 4   DÍA              682502 non-null  int64
 5   MES              682502 non-null  int64
 6   AÑO              682502 non-null  int64
 7   HORA             682502 non-null  int64
 8   FECHA            682502 non-null  object
 9   NOMBRE_CORREDOR  682502 non-null  object
 10  Flujo_tipo       682502 non-null  object
 11  SENTIDO          682502 non-null  object
 12  INICIO           682502 non-null  object
 13  FIN              682502 non-null  object
 14  LONGITUD_KM      682502 non-null  float64
 15  TV_MINUTOS       682502 non-null  float64
 16  VELOCIDAD_KM/H   682502 non-null  float64
 17  TV_MIN/KM        682502 non-null  float64
 18  DIASEM           682502 non-null  int64
 19  NOMBRE_DÍA       682502 non-null  object
dtypes: float64(4), int64(7), object(9)
memory usage: 104.1+ MB

In [ ]:
df3.isnull().sum()

ID                 0
FECHA_HORA         0
TV_[S]             0
CORREDOR           0
DÍA                0
MES                0
AÑO                0
HORA               0
FECHA              0
NOMBRE_CORREDOR    0
Flujo_tipo         0
SENTIDO            0
INICIO             0
FIN                0
LONGITUD_KM        0
TV_MINUTOS         0
VELOCIDAD_KM/H     0
TV_MIN/KM          0
DIASEM             0
NOMBRE_DÍA         0
dtype: int64

In [ ]:
df3.duplicated().sum()

np.int64(1200)

In [ ]:
print(df3.columns)

Index(['ID', 'FECHA_HORA', 'TV_[S]', 'CORREDOR', 'DÍA', 'MES', 'AÑO', 'HORA',
       'FECHA', 'NOMBRE_CORREDOR', 'Flujo_tipo', 'SENTIDO', 'INICIO', 'FIN',
       'LONGITUD_KM', 'TV_MINUTOS', 'VELOCIDAD_KM/H', 'TV_MIN/KM', 'DIASEM',
       'NOMBRE_DÍA'],
      dtype='object')

In [ ]:
df3_clean = df3.copy()

# eliminar duplicados
df3_clean = df3_clean.drop_duplicates()

# limpiar columnas
df3_clean.columns = (
    df3_clean.columns
    .str.strip()
    .str.upper()
    .str.replace(" ", "_")
    .str.replace("/", "_")
)

# limpiar textos
for col in df3_clean.select_dtypes(include='object').columns:
    df3_clean[col] = df3_clean[col].astype(str).str.strip().str.upper()

print(df3_clean.shape)

(681302, 20)

In [ ]:
df3_clean.to_csv("data/processed/velocidad_trafico_limpia.csv", index=False)

In [ ]:
df3_clean.groupby("NOMBRE_CORREDOR")["VELOCIDAD_KM_H"].mean().sort_values().head(10)

NOMBRE_CORREDOR
AVENIDA ORIENTAL       14.243405
AVENIDA FERROCARRIL    19.512723
CALLE 30               20.773860
AVENIDA EL POBLADO     21.612653
AVENIDA 80             22.181410
AVENIDA SAN JUAN       22.944336
AVENIDA 33             28.909332
AVENIDA GUAYABAL       32.510112
AVENIDA LAS PALMAS     40.943452
AUTOPISTA SUR          45.569162
Name: VELOCIDAD_KM_H, dtype: float64

In [ ]:
df3_clean.groupby("HORA")["VELOCIDAD_KM_H"].mean().sort_values().head(10)

HORA
17    25.479101
16    27.314928
18    27.374953
15    28.400693
12    28.889807
14    29.066098
19    29.265262
11    29.484237
10    29.574037
9     29.904735
Name: VELOCIDAD_KM_H, dtype: float64

In [ ]:
df3_clean.groupby("NOMBRE_DÍA")["VELOCIDAD_KM_H"].mean().sort_values()

NOMBRE_DÍA
VIERNES      27.230966
JUEVES       27.831341
MARTES       28.015431
MI�RCOLES    28.104950
LUNES        29.832312
S�BADO       30.690479
DOMINGO      35.779169
Name: VELOCIDAD_KM_H, dtype: float64

In [ ]:
df3_clean.groupby("HORA")["VELOCIDAD_KM_H"].mean()

HORA
6     33.973219
7     31.519741
8     31.619200
9     29.904735
10    29.574037
11    29.484237
12    28.889807
13    29.999329
14    29.066098
15    28.400693
16    27.314928
17    25.479101
18    27.374953
19    29.265262
20    31.696584
Name: VELOCIDAD_KM_H, dtype: float64

In [ ]:
import os
os.listdir("data/processed")

['pasajeros_terminales_limpia.csv', 'velocidad_trafico_limpia.csv']

In [ ]:
import os
os.listdir('/content')

['.config',
 '.ipynb_checkpoints',
 'data',
 'pasajeros_terminales_limpia.csv',
 'camaras_cctv_movilidad_si.csv',
 'Velocidad_y_tiempo_de_viaje_GT.csv',
 'sample_data']

In [ ]:
import pandas as pd

df4 = pd.read_csv("camaras_cctv_movilidad_si.csv")

df4.head()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfa in position 585: invalid start byte

In [ ]:
import pandas as pd

df4 = pd.read_csv("camaras_cctv_movilidad_si.csv", encoding="latin1")

df4.head()

,OBJECTID,Shape,direccion,localizacion,link_foto,link_detalle,longitud,latitud,x_origen_nacional,y_origen_nacional
0,1,"(4711518.0712, 2248071.1384999994)",Cr 83C Cl 33,El Castillo,https://www.medellin.gov.co/simm/camaras-cctv/...,https://www.medellin.gov.co/simm/,-75.608014,6.238633,4.711518e+06,1.181860e+06
1,2,"(4711596.650000002, 2249565.700700002)",Cr 89 Cl 44,Everest,https://www.medellin.gov.co/simm/camaras-cctv/...,https://www.medellin.gov.co/simm/,-75.607371,6.252148,4.711597e+06,1.183354e+06
2,3,"(4710266.759799999, 2252278.7375000007)",Cr 108BB Cl 62D,Túnel de Occidente,https://www.medellin.gov.co/simm/camaras-cctv/...,https://www.medellin.gov.co/simm/,-75.619508,6.276615,4.710267e+06,1.186061e+06
3,4,"(4714887.2167, 2251605.745500002)",Cr 65 Cl 71,La Florida,https://www.medellin.gov.co/simm/camaras-cctv/...,https://www.medellin.gov.co/simm/,-75.577733,6.270738,4.714887e+06,1.185411e+06
4,5,"(4707890.003300001, 2252233.4857)",Cr 134 Cl 59,Vivero Túnel de Occidente,https://www.medellin.gov.co/simm/camaras-cctv/...,https://www.medellin.gov.co/simm/,-75.640979,6.276098,4.707890e+06,1.186004e+06

In [ ]:
df4.info()
df4.isnull().sum()
df4.duplicated().sum()
print(df4.columns)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   OBJECTID           81 non-null     int64
 1   Shape              81 non-null     object
 2   direccion          81 non-null     object
 3   localizacion       81 non-null     object
 4   link_foto          73 non-null     object
 5   link_detalle       81 non-null     object
 6   longitud           81 non-null     float64
 7   latitud            81 non-null     float64
 8   x_origen_nacional  81 non-null     float64
 9   y_origen_nacional  81 non-null     float64
dtypes: float64(4), int64(1), object(5)
memory usage: 6.5+ KB
Index(['OBJECTID', 'Shape', 'direccion', 'localizacion', 'link_foto',
       'link_detalle', 'longitud', 'latitud', 'x_origen_nacional',
       'y_origen_nacional'],
      dtype='object')

In [ ]:
df4.isnull().sum()

OBJECTID             0
Shape                0
direccion            0
localizacion         0
link_foto            8
link_detalle         0
longitud             0
latitud              0
x_origen_nacional    0
y_origen_nacional    0
dtype: int64

In [ ]:
df4.duplicated().sum()

np.int64(0)

In [ ]:
df4_clean = df4.copy()

df4_clean.columns = df4_clean.columns.str.strip().str.upper()

for col in df4_clean.select_dtypes(include='object').columns:
    df4_clean[col] = df4_clean[col].astype(str).str.strip().str.upper()

df4_clean.to_csv("data/processed/camaras_cctv_limpia.csv", index=False)

In [ ]:
os.listdir("data/processed")

['pasajeros_terminales_limpia.csv',
 'camaras_cctv_limpia.csv',
 'velocidad_trafico_limpia.csv']

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
"/content/drive/MyDrive/RetoEafit/"

'/content/drive/MyDrive/RetoEafit/'

In [ ]:
import os
os.listdir('/content')

['.config', 'paradas_de_transporte_pub.csv', 'drive', 'sample_data']

In [ ]:
import pandas as pd

df5 = pd.read_csv("paradas_de_transporte_pub.csv", encoding="latin1")

df5.head()

,OBJECTID,Shape,id_paradero,id_parada,id_ruta,nro_parada,direccion,tipo_parada,recorrido,codigo_ruta,...,empresa,longitud,latitud,x_origen_nacional,y_origen_nacional,tipo_actoadmin,numero_actoadmin,anio_actoadmin,estado,fecha_actualizacion
0,1,"(4714862.777400001, 2252165.179200001)",52588,90098014.0,90098,14.0,"CR 68A x CL 78B, Medellin",Reglamentaria,Origen-Destino,260T,...,Palenque Robledal,-75.577979,6.275795,4.714863e+06,2.252165e+06,NaN,NaN,NaN,NaN,2018-08-01 00:00:00
1,2,"(4712457.373900001, 2246019.061400002)",51532,90003015.0,90003,15.0,"DG 79 9-133, Medellin",Reglamentaria,Origen-Destino,302,...,Autobuses Poblado Laureles,-75.599437,6.220123,4.712457e+06,2.246019e+06,NaN,NaN,NaN,NaN,2018-08-01 00:00:00
2,3,"(4714362.8133, 2254170.956700003)",52335,90075048.0,90075,48.0,"CL 95A x CR 79, Medellin",Reglamentaria,Destino-Origen,252,...,Palenque Robledal,-75.582585,6.293906,4.714363e+06,2.254171e+06,NaN,NaN,NaN,NaN,2018-08-01 00:00:00
3,4,"(4716295.369699999, 2241767.274700001)",53497,90010041.0,90010,41.0,"CR 25B x CL 18A, Medellin",Reglamentaria,Origen-Destino,305,...,Invetrans,-75.564579,6.181853,4.716295e+06,2.241767e+06,NaN,NaN,NaN,NaN,2018-08-01 00:00:00
4,5,"(4716643.501500001, 2249802.825200001)",53687,90014054.0,90014,54.0,"CL 58 45D-96, Medellin",Reglamentaria,Destino-Origen,309D,...,Coinvetrans,-75.561786,6.254516,4.716644e+06,2.249803e+06,NaN,NaN,NaN,NaN,2019-12-05 00:00:00

In [ ]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10043 entries, 0 to 10042
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   OBJECTID             10043 non-null  int64
 1   Shape                10043 non-null  object
 2   id_paradero          10043 non-null  int64
 3   id_parada            10041 non-null  float64
 4   id_ruta              10043 non-null  int64
 5   nro_parada           10043 non-null  float64
 6   direccion            9960 non-null   object
 7   tipo_parada          10043 non-null  object
 8   recorrido            10043 non-null  object
 9   codigo_ruta          10043 non-null  object
 10  nombre_ruta          10043 non-null  object
 11  sistema_ruta         10043 non-null  object
 12  tipo_ruta            10043 non-null  object
 13  empresa              10003 non-null  object
 14  longitud             10043 non-null  float64
 15  latitud              10043 non-null  float64
 16  x_origen_nacional    10043 non-null  float64
 17  y_origen_nacional    10043 non-null  float64
 18  tipo_actoadmin       0 non-null      float64
 19  numero_actoadmin     0 non-null      float64
 20  anio_actoadmin       0 non-null      float64
 21  estado               12 non-null     object
 22  fecha_actualizacion  10043 non-null  object
dtypes: float64(9), int64(3), object(11)
memory usage: 1.8+ MB

In [ ]:
df5.isnull().sum()

OBJECTID                   0
Shape                      0
id_paradero                0
id_parada                  2
id_ruta                    0
nro_parada                 0
direccion                 83
tipo_parada                0
recorrido                  0
codigo_ruta                0
nombre_ruta                0
sistema_ruta               0
tipo_ruta                  0
empresa                   40
longitud                   0
latitud                    0
x_origen_nacional          0
y_origen_nacional          0
tipo_actoadmin         10043
numero_actoadmin       10043
anio_actoadmin         10043
estado                 10031
fecha_actualizacion        0
dtype: int64

In [ ]:
df5.duplicated().sum()

np.int64(0)

In [ ]:
print(df5.columns)

Index(['OBJECTID', 'Shape', 'id_paradero', 'id_parada', 'id_ruta',
       'nro_parada', 'direccion', 'tipo_parada', 'recorrido', 'codigo_ruta',
       'nombre_ruta', 'sistema_ruta', 'tipo_ruta', 'empresa', 'longitud',
       'latitud', 'x_origen_nacional', 'y_origen_nacional', 'tipo_actoadmin',
       'numero_actoadmin', 'anio_actoadmin', 'estado', 'fecha_actualizacion'],
      dtype='object')

In [ ]:
df5_clean = df5.copy()

# eliminar columnas inútiles
df5_clean = df5_clean.drop(columns=[
    "tipo_actoadmin",
    "numero_actoadmin",
    "anio_actoadmin",
    "estado"
], errors="ignore")

# limpiar nombres columnas
df5_clean.columns = (
    df5_clean.columns
    .str.strip()
    .str.upper()
)

# limpiar textos
for col in df5_clean.select_dtypes(include='object').columns:
    df5_clean[col] = df5_clean[col].astype(str).str.strip().str.upper()

print(df5_clean.shape)

(10043, 19)

In [ ]:
import os

os.makedirs("/content/drive/MyDrive/RetoEafit", exist_ok=True)

In [ ]:
df5_clean.to_csv("/content/drive/MyDrive/RetoEafit/paradas_limpia.csv", index=False)

In [ ]:
os.listdir("/content/drive/MyDrive/RetoEafit")

['paradas_limpia.csv']

In [ ]:
import os
os.listdir('/content')

['.config',
 'paradas_de_transporte_pub.csv',
 'drive',
 'rutas_de_transporte_publi.csv',
 'sample_data']

In [ ]:
import pandas as pd

df6 = pd.read_csv("rutas_de_transporte_publi.csv", encoding="latin1")

df6.head()

,OBJECTID,Shape,nombre,id_ruta,codigo,recorrido,from_date,sistema,tipo,empresa,id_gflota,longitud,fecha_actualizacion,Shape_Length
0,1,"(4715457.633850309, 2252270.912431034)",12 de Octubre - Calle 90,90111,263,Origen Destino_Destino Origen,2018-08-01 00:00:00,2B,Directa Centro,Transporte Medellín Castilla,110585.0,19982.069944,2024-12-10 05:11:05,17662.358980
1,2,"(4715462.572997097, 2254279.9873374775)",12 de Octubre - Estación Tricentenario,90113,263i,Origen Destino_Destino Origen,2024-08-27 00:00:00,2B,Integrada,Transporte Medellín Castilla,110712.0,8842.359411,2024-12-10 05:11:05,7138.797803
2,3,"(4716905.228793093, 2255044.7912288033)",12 de Octubre - Estación Tricentenario,90114,263ii,Origen Destino_Destino Origen,2024-08-27 00:00:00,2B,Integrada,Transporte Medellín Castilla,110722.0,2221.247902,2024-12-10 05:11:05,2221.247902
3,4,"(4710541.0989092905, 2249797.5061010984)",20 de Julio,90307,225i-1,Origen Destino_Destino Origen,2024-08-27 00:00:00,8A,Integrada,Metrosan,111912.0,3085.329774,2024-12-10 05:11:05,2279.247112
4,5,"(4716541.9905215055, 2249174.6770195253)",Alcázares de Sucre,90243,91,Origen Destino_Destino Origen,2024-08-27 00:00:00,6F,Directa Centro,Copatra,112915.0,17688.836117,2024-12-10 05:11:05,13085.209787

In [ ]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   OBJECTID             249 non-null    int64
 1   Shape                249 non-null    object
 2   nombre               249 non-null    object
 3   id_ruta              249 non-null    int64
 4   codigo               249 non-null    object
 5   recorrido            249 non-null    object
 6   from_date            249 non-null    object
 7   sistema              249 non-null    object
 8   tipo                 249 non-null    object
 9   empresa              249 non-null    object
 10  id_gflota            239 non-null    float64
 11  longitud             249 non-null    float64
 12  fecha_actualizacion  249 non-null    object
 13  Shape_Length         249 non-null    float64
dtypes: float64(3), int64(2), object(9)
memory usage: 27.4+ KB

In [ ]:
df6.isnull().sum()

OBJECTID                0
Shape                   0
nombre                  0
id_ruta                 0
codigo                  0
recorrido               0
from_date               0
sistema                 0
tipo                    0
empresa                 0
id_gflota              10
longitud                0
fecha_actualizacion     0
Shape_Length            0
dtype: int64

In [ ]:
df6.duplicated().sum()

np.int64(0)

In [ ]:
print(df6.columns)

Index(['OBJECTID', 'Shape', 'nombre', 'id_ruta', 'codigo', 'recorrido',
       'from_date', 'sistema', 'tipo', 'empresa', 'id_gflota', 'longitud',
       'fecha_actualizacion', 'Shape_Length'],
      dtype='object')

In [ ]:
df6_clean = df6.copy()

# limpiar nombres columnas
df6_clean.columns = (
    df6_clean.columns
    .str.strip()
    .str.upper()
)

# limpiar textos
for col in df6_clean.select_dtypes(include='object').columns:
    df6_clean[col] = df6_clean[col].astype(str).str.strip().str.upper()

# opcional: rellenar id_gflota
df6_clean["ID_GFLOTA"] = df6_clean["ID_GFLOTA"].fillna(0)

print(df6_clean.shape)

(249, 14)

In [ ]:
df6_clean.to_csv("/content/drive/MyDrive/RetoEafit/rutas_limpia.csv", index=False)

In [ ]:
os.listdir('/content')

['.config',
 'paradas_de_transporte_pub.csv',
 'drive',
 'velocidad_e_intensidad_vehicular_en_medellin.csv',
 'rutas_de_transporte_publi.csv',
 'sample_data']

In [ ]:
import pandas as pd

df7 = pd.read_csv("velocidad_e_intensidad_vehicular_en_medellin.csv", encoding="latin1")

df7.head()

/tmp/ipykernel_1218/3686504973.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df7 = pd.read_csv("velocidad_e_intensidad_vehicular_en_medellin.csv", encoding="latin1")

,carril,fecha_trafico,fecha,hora,dia,dia_num,mes_num,mes,ano,velocidad_km_h,...,categoria_2,categoria_3,ocupacion,tipo_subsistema,longitud,latitud,identificador_f_v,comuna,codigo_comuna,nombre_comuna
0,XC-1-BOL-65-ENT:ORI-OCC,1/07/2020 0:00,1/07/2020,0,Miercoles,3,7,Julio,2020,27,...,9,3,15,ARS,"833291,8125","1182614,75",V,11 - Laureles Estadio,11,Laureles Estadio
1,XC-1-BOL-65-ENT:ORI-OCC,1/07/2020 1:00,1/07/2020,1,Miercoles,3,7,Julio,2020,24,...,2,0,3,ARS,"833291,8125","1182614,75",V,11 - Laureles Estadio,11,Laureles Estadio
2,XC-1-BOL-65-ENT:ORI-OCC,1/07/2020 2:00,1/07/2020,2,Miercoles,3,7,Julio,2020,21,...,1,1,4,ARS,"833291,8125","1182614,75",V,11 - Laureles Estadio,11,Laureles Estadio
3,XC-1-BOL-65-ENT:ORI-OCC,1/07/2020 3:00,1/07/2020,3,Miercoles,3,7,Julio,2020,18,...,5,1,11,ARS,"833291,8125","1182614,75",V,11 - Laureles Estadio,11,Laureles Estadio
4,XC-1-BOL-65-ENT:ORI-OCC,1/07/2020 4:00,1/07/2020,4,Miercoles,3,7,Julio,2020,18,...,4,3,16,ARS,"833291,8125","1182614,75",V,11 - Laureles Estadio,11,Laureles Estadio

In [ ]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 431490 entries, 0 to 431489
Data columns (total 25 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   carril             431490 non-null  object
 1   fecha_trafico      431490 non-null  object
 2   fecha              431490 non-null  object
 3   hora               431490 non-null  int64
 4   dia                431490 non-null  object
 5   dia_num            431490 non-null  int64
 6   mes_num            431490 non-null  int64
 7   mes                431490 non-null  object
 8   ano                431490 non-null  int64
 9   velocidad_km_h     431490 non-null  int64
 10  corredor           431490 non-null  object
 11  sentido            431490 non-null  object
 12  operacion          393940 non-null  object
 13  intensidad         431490 non-null  int64
 14  categoria_1        431490 non-null  int64
 15  categoria_2        431490 non-null  int64
 16  categoria_3        431490 non-null  int64
 17  ocupacion          431490 non-null  int64
 18  tipo_subsistema    431490 non-null  object
 19  longitud           431490 non-null  object
 20  latitud            431490 non-null  object
 21  identificador_f_v  431490 non-null  object
 22  comuna             405253 non-null  object
 23  codigo_comuna      431490 non-null  int64
 24  nombre_comuna      405253 non-null  object
dtypes: int64(11), object(14)
memory usage: 82.3+ MB

In [ ]:
df7.isnull().sum()

carril                   0
fecha_trafico            0
fecha                    0
hora                     0
dia                      0
dia_num                  0
mes_num                  0
mes                      0
ano                      0
velocidad_km_h           0
corredor                 0
sentido                  0
operacion            37550
intensidad               0
categoria_1              0
categoria_2              0
categoria_3              0
ocupacion                0
tipo_subsistema          0
longitud                 0
latitud                  0
identificador_f_v        0
comuna               26237
codigo_comuna            0
nombre_comuna        26237
dtype: int64

In [ ]:
df7.duplicated().sum()

np.int64(0)

In [ ]:
print(df7.columns)

Index(['carril', 'fecha_trafico', 'fecha', 'hora', 'dia', 'dia_num', 'mes_num',
       'mes', 'ano', 'velocidad_km_h', 'corredor', 'sentido', 'operacion',
       'intensidad', 'categoria_1', 'categoria_2', 'categoria_3', 'ocupacion',
       'tipo_subsistema', 'longitud', 'latitud', 'identificador_f_v', 'comuna',
       'codigo_comuna', 'nombre_comuna'],
      dtype='object')

In [ ]:
df7_clean = df7.copy()

# limpiar nombres columnas
df7_clean.columns = (
    df7_clean.columns
    .str.strip()
    .str.upper()
)

# limpiar textos
for col in df7_clean.select_dtypes(include='object').columns:
    df7_clean[col] = df7_clean[col].astype(str).str.strip().str.upper()

# rellenar faltantes de comuna
df7_clean["COMUNA"] = df7_clean["COMUNA"].fillna("SIN DATO")
df7_clean["NOMBRE_COMUNA"] = df7_clean["NOMBRE_COMUNA"].fillna("SIN DATO")

print(df7_clean.shape)

(431490, 25)

In [ ]:
df7_clean.to_csv("/content/drive/MyDrive/RetoEafit/intensidad_vehicular_limpia.csv", index=False)

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [ ]:
import pandas as pd

df2_clean = pd.read_csv("/content/drive/MyDrive/RetoEafit/pasajeros_terminales_limpia.csv")
df3_clean = pd.read_csv("/content/drive/MyDrive/RetoEafit/velocidad_trafico_limpia.csv")
df4_clean = pd.read_csv("/content/drive/MyDrive/RetoEafit/camaras_cctv_limpia.csv")
df5_clean = pd.read_csv("/content/drive/MyDrive/RetoEafit/paradas_limpia.csv")
df6_clean = pd.read_csv("/content/drive/MyDrive/RetoEafit/rutas_limpia.csv")
df7_clean = pd.read_csv("/content/drive/MyDrive/RetoEafit/intensidad_vehicular_limpia.csv")

print("Bases cargadas correctamente")

/tmp/ipykernel_5642/3830850618.py:4: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df3_clean = pd.read_csv("/content/drive/MyDrive/RetoEafit/velocidad_trafico_limpia.csv")
/tmp/ipykernel_5642/3830850618.py:8: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df7_clean = pd.read_csv("/content/drive/MyDrive/RetoEafit/intensidad_vehicular_limpia.csv")

Bases cargadas correctamente

In [ ]:
bases = {
    "pasajeros": df2_clean,
    "trafico": df3_clean,
    "camaras": df4_clean,
    "paradas": df5_clean,
    "rutas": df6_clean,
    "intensidad": df7_clean
}

In [ ]:
for nombre, df in bases.items():
    print(f"\n===== {nombre.upper()} =====")
    columnas_texto = df.select_dtypes(include='object').columns

    for col in columnas_texto:
        if df[col].nunique() <= 15:
            print(f"\n📌 {col}")
            print(df[col].value_counts())

===== PASAJEROS =====

📌 IDSUCURSAL
IDSUCURSAL
TERMINAL NORTE    62541
TERMINAL SUR      22758
Name: count, dtype: int64

===== TRAFICO =====

📌 NOMBRE_CORREDOR
NOMBRE_CORREDOR
AUTOPISTA NORTE        64469
AVENIDA LAS PALMAS     64165
AVENIDA EL POBLADO     64047
AVENIDA 33             63855
AVENIDA SAN JUAN       63661
AVENIDA 80             63098
AVENIDA GUAYABAL       62651
CALLE 30               62498
AVENIDA FERROCARRIL    62342
AVENIDA ORIENTAL       45921
AVENIDA REGIONAL       32317
AUTOPISTA SUR          32278
Name: count, dtype: int64

📌 FLUJO_TIPO
FLUJO_TIPO
INTERRUMPIDO    488073
CONTINUO        193229
Name: count, dtype: int64

📌 SENTIDO
SENTIDO
NS    245691
SN    245597
WE     95014
EW     95000
Name: count, dtype: int64

📌 NOMBRE_DÍA
NOMBRE_DÍA
MARTES       102366
LUNES        102051
MI�RCOLES    101380
VIERNES      101110
JUEVES       100808
S�BADO        87238
DOMINGO       86349
Name: count, dtype: int64

===== CAMARAS =====

📌 LINK_DETALLE
LINK_DETALLE
HTTPS://WWW.MEDELLIN.GOV.CO/SIMM/    81
Name: count, dtype: int64

===== PARADAS =====

📌 TIPO_PARADA
TIPO_PARADA
REGLAMENTARIA    10043
Name: count, dtype: int64

📌 RECORRIDO
RECORRIDO
ORIGEN-DESTINO    5237
DESTINO-ORIGEN    4806
Name: count, dtype: int64

📌 TIPO_RUTA
TIPO_RUTA
DIRECTA CENTRO       6476
INTEGRADA            1911
CIRCULAR             1163
DIRECTA NO CENTRO     493
Name: count, dtype: int64

===== RUTAS =====

📌 RECORRIDO
RECORRIDO
ORIGEN DESTINO_DESTINO ORIGEN    249
Name: count, dtype: int64

📌 TIPO
TIPO
DIRECTA CENTRO       155
INTEGRADA             55
DIRECTA NO CENTRO     20
CIRCULAR              19
Name: count, dtype: int64

📌 FECHA_ACTUALIZACION
FECHA_ACTUALIZACION
2024-12-10 05:11:05    249
Name: count, dtype: int64

===== INTENSIDAD =====

📌 DIA
DIA
JUEVES       67923
MIERCOLES    67772
VIERNES      66989
DOMINGO      57772
LUNES        57633
SABADO       57421
MARTES       55980
Name: count, dtype: int64

📌 MES
MES
JULIO     377193
AGOSTO     54297
Name: count, dtype: int64

📌 SENTIDO
SENTIDO
SN       149580
NS       119184
WE        68415
EW        67962
0         23416
WE-EW      2192
NS-SN       741
Name: count, dtype: int64

📌 OPERACION
OPERACION
INTERRUMPIDO       274876
CONTINUO            85425
NAN                 37550
SEMINTERRUMPIDO     33639
Name: count, dtype: int64

📌 TIPO_SUBSISTEMA
TIPO_SUBSISTEMA
ARS     219523
CCTV    185730
FT       26237
Name: count, dtype: int64

📌 IDENTIFICADOR_F_V
IDENTIFICADOR_F_V
V    422821
F      8669
Name: count, dtype: int64

📌 NOMBRE_COMUNA
NOMBRE_COMUNA
EL POBLADO                                        114130
LA CANDELARIA                                      73163
LAURELES ESTADIO                                   72682
SISTEMA VIAL DEL RÏ¿½Ï¿½Ï¿½O                       43035
CASTILLA                                           34835
NAN                                                26237
BELEN                                              24794
GUAYABAL                                           18309
ROBLEDO                                            15686
LA AMERICA                                          5645
CORREGIMIENTO DE SAN CRISTÏ¿½Ï¿½Ï¿½BAL              2972
SISTEMA VIAL DEL RÏ¿½Ï¿½Ï¿½Ï¿½Ï¿½Ï¿½O                  1
SISTEMA VIAL DEL RÏ¿½Ï¿½Ï¿½Ï¿½Ï¿½Ï¿½Ï¿½Ï¿½Ï¿½O         1
Name: count, dtype: int64

In [ ]:
# ---------- TRAFICO ----------
df3_clean["NOMBRE_DÍA"] = df3_clean["NOMBRE_DÍA"].replace({
    "MI�RCOLES": "MIERCOLES",
    "S�BADO": "SABADO"
})

# ---------- INTENSIDAD ----------
df7_clean["OPERACION"] = df7_clean["OPERACION"].replace("NAN", "SIN DATO")

df7_clean["SENTIDO"] = df7_clean["SENTIDO"].replace({
    "0": "SIN DATO",
    "WE-EW": "WE",
    "NS-SN": "NS"
})

# limpiar comunas raras
valores_invalidos = [
    "SISTEMA VIAL DEL RI",
    "CORREGIMIENTO DE SAN CRISTOBAL"
]

df7_clean["NOMBRE_COMUNA"] = df7_clean["NOMBRE_COMUNA"].replace(valores_invalidos, "SIN DATO")

In [ ]:
df3_clean["NOMBRE_DÍA"].value_counts()

NOMBRE_DÍA
MARTES       102366
LUNES        102051
MIERCOLES    101380
VIERNES      101110
JUEVES       100808
SABADO        87238
DOMINGO       86349
Name: count, dtype: int64

In [ ]:
df7_clean["SENTIDO"].value_counts()

SENTIDO
SN          149580
NS          119925
WE           70607
EW           67962
SIN DATO     23416
Name: count, dtype: int64

In [ ]:
df7_clean["NOMBRE_COMUNA"].value_counts().head(15)

NOMBRE_COMUNA
EL POBLADO                                        114130
LA CANDELARIA                                      73163
LAURELES ESTADIO                                   72682
SISTEMA VIAL DEL RÏ¿½Ï¿½Ï¿½O                       43035
CASTILLA                                           34835
NAN                                                26237
BELEN                                              24794
GUAYABAL                                           18309
ROBLEDO                                            15686
LA AMERICA                                          5645
CORREGIMIENTO DE SAN CRISTÏ¿½Ï¿½Ï¿½BAL              2972
SISTEMA VIAL DEL RÏ¿½Ï¿½Ï¿½Ï¿½Ï¿½Ï¿½O                  1
SISTEMA VIAL DEL RÏ¿½Ï¿½Ï¿½Ï¿½Ï¿½Ï¿½Ï¿½Ï¿½Ï¿½O         1
Name: count, dtype: int64

In [ ]:
# corregir NAN texto
df7_clean["NOMBRE_COMUNA"] = df7_clean["NOMBRE_COMUNA"].replace("NAN", "SIN DATO")

# corregir sistema vial del rio
df7_clean.loc[
    df7_clean["NOMBRE_COMUNA"].str.contains("SISTEMA VIAL", na=False),
    "NOMBRE_COMUNA"
] = "SISTEMA VIAL DEL RIO"

# corregir corregimiento san cristobal
df7_clean.loc[
    df7_clean["NOMBRE_COMUNA"].str.contains("CORREGIMIENTO", na=False),
    "NOMBRE_COMUNA"
] = "CORREGIMIENTO DE SAN CRISTOBAL"

In [ ]:
df7_clean["NOMBRE_COMUNA"].value_counts().head(15)

NOMBRE_COMUNA
EL POBLADO          114130
LA CANDELARIA        73163
LAURELES ESTADIO     72682
SIN DATO             72246
CASTILLA             34835
BELEN                24794
GUAYABAL             18309
ROBLEDO              15686
LA AMERICA            5645
Name: count, dtype: int64

In [ ]:
df7_clean[df7_clean["NOMBRE_COMUNA"]=="SISTEMA VIAL DEL RIO"].shape

(0, 25)

In [ ]:
df7_clean[df7_clean["NOMBRE_COMUNA"]=="CORREGIMIENTO DE SAN CRISTOBAL"].shape

(0, 25)

In [ ]:
df7_clean["NOMBRE_COMUNA"].unique()

array(['LAURELES ESTADIO', 'BELEN', 'EL POBLADO', 'LA CANDELARIA',
       'SIN DATO', 'ROBLEDO', 'LA AMERICA', 'CASTILLA', 'GUAYABAL'],
      dtype=object)